# Generated by Django 2.2 on 2019-07-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190711_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('title', 'summary')},
        ),
    ]
