# Generated by Django 2.2.3 on 2019-08-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190711_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('title', 'project_description')},
        ),
        migrations.RemoveField(
            model_name='job',
            name='summary',
        ),
        migrations.AddField(
            model_name='job',
            name='project_description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='job',
            name='technologies',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
